// nextlearning/src/features/dashboard/Footer.tsx
const Footer = () => {
    return (
      <div>
          <footer className="main-footer">
              <strong></strong>
              <div className="float-right d-none d-sm-inline-block">
                  <b>Version:</b>
              </div>
          </footer>
      </div>
    );
};

export default Footer

// VueLearning/components/dashboard/Footer.vue
<template>
  <footer class="main-footer">
    <strong>Simple Chat</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version:</b> {{ version }}
    </div>
  </footer>
</template>

<script>

export default {
  name: "Footer",
  computed: {
    version() {
      return 1
    }
  }
}
</script>

<style scoped>

</style>
