// VueLearning/components/sidebarContainer/SidebarContainer.vue
<template>
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <Logo/>
    <div class="sidebar">

    </div>
  </aside>
</template>

<script>
import Logo from "@/components/sidebarContainer/Logo";
export default {
  name: "SidebarContainer",
  components: {Logo}
}
</script>

<style scoped>

</style>

// nextlearning/src/features/dashboard/sideBar/SideBarContainer.tsx
import {Fragment} from "react";
import Logo from "./Logo";

const SideBarContainer = () => {
    return (
        <Fragment>
            <aside className="main-sidebar sidebar-dark-primary elevation-4">
                <Logo/>
                <div className="sidebar">

                </div>
            </aside>
        </Fragment>
    )
}

export default SideBarContainer
