// VueLearning/VueLearning/src/components/dashboard/Footer.vue
<template>
  <footer class="main-footer">
    <strong>{{bannerText}}</strong>
    <div class="float-right d-none d-sm-inline-block">
      <b>Version:</b> {{ version }}
    </div>
  </footer>
</template>

<script>
import {mapGetters} from "vuex";

export default {
  name: "Footer",

  computed: {
    ...mapGetters(["bannerText","version"])
  }
}
</script>

<style scoped>

</style>

// nextlearning/src/features/dashboard/Footer.tsx
const Footer = () => {
    return (
      <div>
          <footer className="main-footer">
              <strong></strong>
              <div className="float-right d-none d-sm-inline-block">
                  <b>Version:</b>
              </div>
          </footer>
      </div>
    );
};

export default Footer
