// VueLearning/components/dashboard/NavBar.vue
<template>
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
  <!-- Left navbarContainer links -->
  <ul class="navbar-nav">
    <li class="nav-item">
    <a class="nav-link" data-widget="pushmenu" role="button"><i
      class="fas fa-bars"/></a>
    </li>
  </ul>
  <!-- Right navbarContainer links -->
  <ul class="navbar-nav ml-auto">
    <li class="nav-item">
    </li>
    <li class="nav-item">
      <a class="nav-link" data-widget="control-sidebar" data-slide="true" role="button"
      title="Switch to Dark mode">
      <i class="fas fa-moon"/>
      </a>
    </li>
    <li class="nav-item">
    </li>
  </ul>
  </nav>
  <!-- /.navbarContainer -->
</template>

<script>
export default {
  name: "NavBar"
}
</script>

<style scoped>

</style>

// nextlearning/src/features/dashboard/NavBar.tsx
import {Fragment} from "react";
import {useAppSelector} from "../../app/hooks";
import {selectDarkMode} from "../darkMode/darkModeSlice";
import ToggleSideBarBtn from "../interface/toggleSideBarBtn";
import DarkModeBtn from "../darkMode/darkMode";

const NavBar = () => {
    const darkMode = useAppSelector(selectDarkMode)

    return (
        <Fragment>
            <nav
                className={`main-header navbar navbar-expand ${darkMode ? "navbar-dark" : "navbar-white navbar-light"}`}>
                <ul className="navbar-nav">
                    <ToggleSideBarBtn/>
                </ul>
                {/*<!-- Right navbarContainer links -->*/}
                <ul className="navbar-nav ml-auto">
                    <li className="nav-item">
                        <DarkModeBtn/>
                    </li>
                </ul>
            </nav>
        </Fragment>
    )
};

export default NavBar
