// nextlearning/src/pages/index.tsx
import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from "../features/dashboard/Footer";


const IndexPage: NextPage = () => {
    return (
        <div className="sidebar-mini layout-fixed sidebar-height dark-mode sidebar-collapse">
            <div className="wrapper">
                <div className="content-wrapper">
                    <span>Content here</span>
                </div>
                <Footer/>
            </div>
        </div>
)
}

export default IndexPage

// VueLearning/VueLearning/src/pages/index.vue
<template>
  <div class="sidebar-mini layout-fixed sidebar-height"
       :class="[darkMode ? 'dark-mode': '', showSidebar ? 'sidebar-collapse' : '']"
  >
    <div class="wrapper">
      <NavBar/>
      <SidebarContainer/>
      <div class="content-wrapper">
        <span>Content here</span>
      </div>
      <Footer/>
    </div>
  </div>
</template>

<script>
import SidebarContainer from "@/components/dashboard/sidebarContainer/SidebarContainer";
import Footer from "@/components/dashboard/Footer";
import NavBar from "@/components/dashboard/NavBar";
import {mapGetters} from "vuex";

export default {
  components: {
    NavBar,
    Footer,
    SidebarContainer
  },

  computed: {
    ...mapGetters(["darkMode","showSidebar"])
  },
}
</script>

<style scoped>
.sidebar-height {
  height: auto
}
</style>
